export const SEARCH_CITIES_PENDING = 'SEARCH_CITIES_PENDING';
export const SEARCH_CITIES_ERROR = 'SEARCH_CITIES_ERROR';
export const SEARCH_CITIES_SUCCESS = 'SEARCH_CITIES_SUCCUSS';

export const REQUEST_CURRENT_CITY_PENDING = 'REQUEST_CHOOSE_CITY_PENDING';
export const REQUEST_CURRENT_CITY_SUCCESS = 'REQUEST_CHOOSE_CITY_SUCCESS';
export const REQUEST_CURRENT_CITY_ERROR = 'REQUEST_CHOOSE_CITY_ERROR';
export const NULLIFY_ERRORS = 'NULLIFY_ERRORS';

export const ADD_OR_REMOVE_FAVORITES = 'ADD_OR_REMOVE_FAVORITES';

export const TOGGLE_FAVORITES = 'REMOVE_FROM_FAVORITES';
export const TOGGLE_CELSIUS_FAHRENHEIT = 'TOGGLE_CELSIUS_FAHRENHEIT';
export const TOGGLE_DARK_LIGHT_THEME = 'TOGGLE_DARK_LIGHT_THEME';
